- name: Production Deployment
  hosts: webserver
  become: yes

  tasks:
    - name: creating mnt Dir
      file:
       path: /root/mnt
       state: directory
    - name: download tomcat
      action: get_url url=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.zip dest=/root/mnt

    - name: install jdk
      action: yum pkg=java-1.8.0-openjdk-devel.x86_64 state=present

    - name: unzip tomcat
      ansible.builtin.unarchive: src=/root/mnt/apache-tomcat-9.0.63.zip dest=/root/mnt remote_src=yes

   - name: change permission
     shell: 'chmod -R 777 /root/mnt/apache-tomcat-9.0.63.zip/bin'


    - name: Run Tomcat
      command: nohup /root/mnt/apache-tomcat-9.0.63.zip/bin/startup.sh

    - name: deploy sample war
      action: copy src=/root/mnt/Jenkins_path/workspace/GOL@2/gameoflife-web/target/gameoflife.war dest=/root/mnt/apache-tomcat-9.0.63.zip/webapps

