- name: Production Deployment
  hosts: webserver
  become: yes

  tasks:
    - name: creating mnt Dir
      file:
       path: /tmp
       state: directory
    - name: download tomcat
      action: get_url url=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.63/bin/apache-tomcat-9.0.63.zip dest=/mnt

    - name: install jdk
      action: yum pkg=java-1.8.0-openjdk-devel.x86_64 state=present

    - name: unzip tomcat
      ansible.builtin.unarchive: src=/mnt/apache-tomcat-9.0.63.zip dest=/mnt remote_src=yes

    - name: change permission
      shell: 'chmod -R 777 /mnt/apache-tomcat-9.0.63.zip/bin'

    - name: Run Tomcat
      command: nohup /mnt/apache-tomcat-9.0.63.zip/bin/startup.sh

    - name: deploy sample war
      action: copy src=/mnt/Jenkins_path/workspace/GOL@2/gameoflife-web/target/gameoflife.war dest=/mnt/apache-tomcat-9.0.63.zip/webapps
